COUNTRIES = ((u'', u'Country'),
            (u'AFG', u'Afghanistan'),
            (u'ALA', u'\xc5land Islands'),
            (u'ALB', u'Albania'),
            (u'DZA', u'Algeria'),
            (u'ASM', u'American Samoa'),
            (u'AND', u'Andorra'),
            (u'AGO', u'Angola'),
            (u'AIA', u'Anguilla'),
            (u'ATG', u'Antigua and Barbuda'),
            (u'ARG', u'Argentina'),
            (u'ARM', u'Armenia'),
            (u'ABW', u'Aruba'),
            (u'AUS', u'Australia'),
            (u'AUT', u'Austria'),
            (u'AZE', u'Azerbaijan'),
            (u'BHS', u'Bahamas'),
            (u'BHR', u'Bahrain'),
            (u'BGD', u'Bangladesh'),
            (u'BRB', u'Barbados'),
            (u'BLR', u'Belarus'),
            (u'BEL', u'Belgium'),
            (u'BLZ', u'Belize'),
            (u'BEN', u'Benin'),
            (u'BMU', u'Bermuda'),
            (u'BTN', u'Bhutan'),
            (u'BOL', u'Bolivia (Plurinational State of)'),
            (u'BES', u'Bonaire, Saint Eustatius and Saba'),
            (u'BIH', u'Bosnia and Herzegovina'),
            (u'BWA', u'Botswana'),
            (u'BRA', u'Brazil'),
            (u'VGB', u'British Virgin Islands'),
            (u'BRN', u'Brunei Darussalam'),
            (u'BGR', u'Bulgaria'),
            (u'BFA', u'Burkina Faso'),
            (u'BDI', u'Burundi'),
            (u'KHM', u'Cambodia'),
            (u'CMR', u'Cameroon'),
            (u'CAN', u'Canada'),
            (u'CPV', u'Cape Verde'),
            (u'CYM', u'Cayman Islands'),
            (u'CAF', u'Central African Republic'),
            (u'TCD', u'Chad'),
            (u'', u'Channel Islands'),
            (u'CHL', u'Chile'),
            (u'CHN', u'China'),
            (u'HKG', u'China,  Hong Kong Special Administrative Region'),
            (u'MAC', u'China, Macao Special Administrative Region'),
            (u'COL', u'Colombia'),
            (u'COM', u'Comoros'),
            (u'COG', u'Congo'),
            (u'COK', u'Cook Islands'),
            (u'CRI', u'Costa Rica'),
            (u'CIV', u"C\xf4te d'Ivoire"),
            (u'HRV', u'Croatia'),
            (u'CUB', u'Cuba'),
            (u'CUW', u'Cura\xe7ao'),
            (u'CYP', u'Cyprus'),
            (u'CZE', u'Czech Republic'),
            (u'PRK', u"Democratic People's Republic of Korea"),
            (u'COD', u'Democratic Republic of the Congo'),
            (u'DNK', u'Denmark'),
            (u'DJI', u'Djibouti'),
            (u'DMA', u'Dominica'),
            (u'DOM', u'Dominican Republic'),
            (u'ECU', u'Ecuador'),
            (u'EGY', u'Egypt'),
            (u'SLV', u'El Salvador'),
            (u'GNQ', u'Equatorial Guinea'),
            (u'ERI', u'Eritrea'),
            (u'EST', u'Estonia'),
            (u'ETH', u'Ethiopia'),
            (u'FRO', u'Faeroe Islands'),
            (u'FLK', u'Falkland Islands (Malvinas)'),
            (u'FJI', u'Fiji'),
            (u'FIN', u'Finland'),
            (u'FRA', u'France'),
            (u'GUF', u'French Guiana'),
            (u'PYF', u'French Polynesia'),
            (u'GAB', u'Gabon'),
            (u'GMB', u'Gambia'),
            (u'GEO', u'Georgia'),
            (u'DEU', u'Germany'),
            (u'GHA', u'Ghana'),
            (u'GIB', u'Gibraltar'),
            (u'GRC', u'Greece'),
            (u'GRL', u'Greenland'),
            (u'GRD', u'Grenada'),
            (u'GLP', u'Guadeloupe'),
            (u'GUM', u'Guam'),
            (u'GTM', u'Guatemala'),
            (u'GGY', u'Guernsey'),
            (u'GIN', u'Guinea'),
            (u'GNB', u'Guinea-Bissau'),
            (u'GUY', u'Guyana'),
            (u'HTI', u'Haiti'),
            (u'VAT', u'Holy See'),
            (u'HND', u'Honduras'),
            (u'HUN', u'Hungary'),
            (u'ISL', u'Iceland'),
            (u'IND', u'India'),
            (u'IDN', u'Indonesia'),
            (u'IRN', u'Iran (Islamic Republic of)'),
            (u'IRQ', u'Iraq'),
            (u'IRL', u'Ireland'),
            (u'IMN', u'Isle of Man'),
            (u'ISR', u'Israel'),
            (u'ITA', u'Italy'),
            (u'JAM', u'Jamaica'),
            (u'JPN', u'Japan'),
            (u'JEY', u'Jersey'),
            (u'JOR', u'Jordan'),
            (u'KAZ', u'Kazakhstan'),
            (u'KEN', u'Kenya'),
            (u'KIR', u'Kiribati'),
            (u'KWT', u'Kuwait'),
            (u'KGZ', u'Kyrgyzstan'),
            (u'LAO', u"Lao People's Democratic Republic"),
            (u'LVA', u'Latvia'),
            (u'LBN', u'Lebanon'),
            (u'LSO', u'Lesotho'),
            (u'LBR', u'Liberia'),
            (u'LBY', u'Libya'),
            (u'LIE', u'Liechtenstein'),
            (u'LTU', u'Lithuania'),
            (u'LUX', u'Luxembourg'),
            (u'MDG', u'Madagascar'),
            (u'MWI', u'Malawi'),
            (u'MYS', u'Malaysia'),
            (u'MDV', u'Maldives'),
            (u'MLI', u'Mali'),
            (u'MLT', u'Malta'),
            (u'MHL', u'Marshall Islands'),
            (u'MTQ', u'Martinique'),
            (u'MRT', u'Mauritania'),
            (u'MUS', u'Mauritius'),
            (u'MYT', u'Mayotte'),
            (u'MEX', u'Mexico'),
            (u'FSM', u'Micronesia (Federated States of)'),
            (u'MCO', u'Monaco'),
            (u'MNG', u'Mongolia'),
            (u'MNE', u'Montenegro'),
            (u'MSR', u'Montserrat'),
            (u'MAR', u'Morocco'),
            (u'MOZ', u'Mozambique'),
            (u'MMR', u'Myanmar'),
            (u'NAM', u'Namibia'),
            (u'NRU', u'Nauru'),
            (u'NPL', u'Nepal'),
            (u'NLD', u'Netherlands'),
            (u'NCL', u'New Caledonia'),
            (u'NZL', u'New Zealand'),
            (u'NIC', u'Nicaragua'),
            (u'NER', u'Niger'),
            (u'NGA', u'Nigeria'),
            (u'NIU', u'Niue'),
            (u'NFK', u'Norfolk Island'),
            (u'MNP', u'Northern Mariana Islands'),
            (u'NOR', u'Norway'),
            (u'PSE', u'Occupied Palestinian Territory'),
            (u'OMN', u'Oman'),
            (u'PAK', u'Pakistan'),
            (u'PLW', u'Palau'),
            (u'PAN', u'Panama'),
            (u'PNG', u'Papua New Guinea'),
            (u'PRY', u'Paraguay'),
            (u'PER', u'Peru'),
            (u'PHL', u'Philippines'),
            (u'PCN', u'Pitcairn'),
            (u'POL', u'Poland'),
            (u'PRT', u'Portugal'),
            (u'PRI', u'Puerto Rico'),
            (u'QAT', u'Qatar'),
            (u'KOR', u'Republic of Korea'),
            (u'MDA', u'Republic of Moldova'),
            (u'REU', u'R\xe9union'),
            (u'ROU', u'Romania'),
            (u'RUS', u'Russian Federation'),
            (u'RWA', u'Rwanda'),
            (u'BLM', u'Saint-Barth\xe9lemy'),
            (u'SHN', u'Saint Helena'),
            (u'KNA', u'Saint Kitts and Nevis'),
            (u'LCA', u'Saint Lucia'),
            (u'MAF', u'Saint-Martin (French part)'),
            (u'SPM', u'Saint Pierre and Miquelon'),
            (u'VCT', u'Saint Vincent and the Grenadines'),
            (u'WSM', u'Samoa'),
            (u'SMR', u'San Marino'),
            (u'STP', u'Sao Tome and Principe'),
            (u'SAU', u'Saudi Arabia'),
            (u'SEN', u'Senegal'),
            (u'SRB', u'Serbia'),
            (u'SYC', u'Seychelles'),
            (u'SLE', u'Sierra Leone'),
            (u'SGP', u'Singapore'),
            (u'SXM', u'Sint Maarten (Dutch part)'),
            (u'SVK', u'Slovakia'),
            (u'SVN', u'Slovenia'),
            (u'SLB', u'Solomon Islands'),
            (u'SOM', u'Somalia'),
            (u'ZAF', u'South Africa'),
            (u'SSD', u'South Sudan'),
            (u'ESP', u'Spain'),
            (u'LKA', u'Sri Lanka'),
            (u'SDN', u'Sudan'),
            (u'SUR', u'Suri    name'),
            (u'SJM', u'Svalbard and Jan Mayen Islands'),
            (u'SWZ', u'Swaziland'),
            (u'SWE', u'Sweden'),
            (u'CHE', u'Switzerland'),
            (u'SYR', u'Syrian Arab Republic'),
            (u'TJK', u'Tajikistan'),
            (u'THA', u'Thailand'),
            (u'MKD', u'The former Yugoslav Republic of Macedonia'),
            (u'TLS', u'Timor-Leste'),
            (u'TGO', u'Togo'),
            (u'TKL', u'Tokelau'),
            (u'TON', u'Tonga'),
            (u'TTO', u'Trinidad and Tobago'),
            (u'TUN', u'Tunisia'),
            (u'TUR', u'Turkey'),
            (u'TKM', u'Turkmenistan'),
            (u'TCA', u'Turks and Caicos Islands'),
            (u'TUV', u'Tuvalu'),
            (u'UGA', u'Uganda'),
            (u'UKR', u'Ukraine'),
            (u'ARE', u'United Arab Emirates'),
            (u'GBR', u'United Kingdom of Great Britain and Northern Ireland'),
            (u'TZA', u'United Republic of Tanzania'),
            (u'USA', u'United States of America'),
            (u'VIR', u'United States Virgin Islands'),
            (u'URY', u'Uruguay'),
            (u'UZB', u'Uzbekistan'),
            (u'VUT', u'Vanuatu'),
            (u'VEN', u'Venezuela (Bolivarian Republic of)'),
            (u'VNM', u'Viet Nam'),
            (u'WLF', u'Wallis and Futuna Islands'),
            (u'ESH', u'Western Sahara'),
            (u'YEM', u'Yemen'),
            (u'ZMB', u'Zambia'),
            (u'ZWE', u'Zimbabwe'))